robot_radius: 0.25
# footprint: [[-0.12, -0.12], [-0.12, 0.12], [0.12, 0.12], [0.12, -0.12]] 

obstacle_range: 3.0 
raytrace_range: 3.5 
inflation_radius: 0.2 # 0.2
min_obstacle_height: 0.3 # 0.3


cost_scaling_factor: 3.0


map_type: costmap

observation_sources: depth_camera

depth_camera: {sensor_frame: depth_camera, data_type: PointCloud, topic: /realsense/depth/pointcloud, marking: true, clearing: true}
