local_costmap:
  global_frame: world 
  robot_base_frame: true_body 

  update_frequency: 10.0 
  publish_frequency: 10.0 
  transform_tolerance: 0.5 


  rolling_window: true 
  width: 3 
  height: 3 
  resolution: 0.05 

